language: php

php:
    - 5.5
    - 5.6
    - hhvm

matrix:
    include:
        - php: 5.5
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
    - travis_retry wget https://scrutinizer-ci.com/ocular.phar

script:
    - bin/phpunit

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then php ocular.phar code-coverage:upload --format=php-clover var/build/logs/clover.xml; fi
